### PR TITLE
Revert "Allow the use of multiple arguments"

### PR DESCRIPTION
**Pull request by timja**
Reverts jenkinsci/docker-inbound-agent#254

### CODE REVIEW

**Comment by MarkEWaite** [comment]
@timja was it intentional that a new tag was placed on the repository for [4.12.2-4](https://github.com/jenkinsci/docker-inbound-agent/releases/tag/4.12.2-4) rather than using 4.11.2-4?  I thought that the initial segment of the tag was the remoting version used in the image with the ending segment used to increment version number of the image for that remoting version.

**Comment by timja** [comment]
That was release drafter being 'helpful' and me not triple checking 😢 

Thanks

**Comment by MarkEWaite** [comment]
Is there any reasonable way that we can remove the 4.12.2-4 tag for the windows images on Dockerhub?

**Comment by timja** [comment]
> Is there any reasonable way that we can remove the 4.12.2-4 tag for the windows images on Dockerhub?

https://stackoverflow.com/a/60112300/4951015

**Comment by MarkEWaite** [comment]
> seems so: https://stackoverflow.com/a/60112300/4951015

That looks easy enough.  Any caveats or major risks that should be considered before I remove 

* 4.12.2-4-jdk11-nanoserver-1809
* 4.12.2-4-windowsservercore-ltsc2019
* 4.12.2-4-jdk8-windowsservercore-ltsc2019
* 4.12.2-4-nanoserver-1809
* 4.12.2-4-jdk8-nanoserver-1809
* 4.12.2-4-jdk11-windowsservercore-ltsc2019

If a user has already pulled the image, they may be surprised that it no longer exists.  Since the image has existed for less than 24 hours, it seems safe to remove them.

**Comment by timja** [comment]
Agree

**Comment by MarkEWaite** [comment]
Deletions have been done.  I fear that I may have also deleted one of the nanoserver images for 4.11.2-4 due to mouse clumsiness.  Let me know if there are reports of issues

**Comment by basil** [comment]
Sorry for the trouble and thanks for reverting this.

**Comment by sharkannon** [comment]
It appears that the latest tag right now is still pointing to 4.11.2-3

```
➜  ~ docker pull jenkins/inbound-agent:4.11.2-3-jdk11                                                                                          
4.11.2-3-jdk11: Pulling from jenkins/inbound-agent
Digest: sha256:296579aa37138cd1ea493efb5e554e2061a8f851a46762c32bfdebe9d0d71aa3
Status: Image is up to date for jenkins/inbound-agent:4.11.2-3-jdk11
docker.io/jenkins/inbound-agent:4.11.2-3-jdk11
➜  ~ docker inspect --format='{{index .RepoDigests 0}}' jenkins/inbound-agent:4.11.2-3-jdk11
jenkins/inbound-agent@sha256:296579aa37138cd1ea493efb5e554e2061a8f851a46762c32bfdebe9d0d71aa3
```

```
docker.io/jenkins/inbound-agent:latest
➜  ~ docker inspect --format='{{index .RepoDigests 0}}' jenkins/inbound-agent:latest        
jenkins/inbound-agent@sha256:296579aa37138cd1ea493efb5e554e2061a8f851a46762c32bfdebe9d0d71aa3
```

**Comment by timja** [comment]
It should have been released 12 hours ago, I've retriggered it, all the digests on the docker hub UI look different.

Did that fix it for you?

**Comment by amitlalani** [comment]
> It appears that the latest tag right now is still pointing to 4.11.2-3
> 
> ```
> ➜  ~ docker pull jenkins/inbound-agent:4.11.2-3-jdk11                                                                                          
> 4.11.2-3-jdk11: Pulling from jenkins/inbound-agent
> Digest: sha256:296579aa37138cd1ea493efb5e554e2061a8f851a46762c32bfdebe9d0d71aa3
> Status: Image is up to date for jenkins/inbound-agent:4.11.2-3-jdk11
> docker.io/jenkins/inbound-agent:4.11.2-3-jdk11
> ➜  ~ docker inspect --format='{{index .RepoDigests 0}}' jenkins/inbound-agent:4.11.2-3-jdk11
> jenkins/inbound-agent@sha256:296579aa37138cd1ea493efb5e554e2061a8f851a46762c32bfdebe9d0d71aa3
> ```
> 
> ```
> ➜  ~ docker pull jenkins/inbound-agent:latest                                               
> latest: Pulling from jenkins/inbound-agent
> Digest: sha256:296579aa37138cd1ea493efb5e554e2061a8f851a46762c32bfdebe9d0d71aa3
> Status: Downloaded newer image for jenkins/inbound-agent:latest
> docker.io/jenkins/inbound-agent:latest
> ➜  ~ docker inspect --format='{{index .RepoDigests 0}}' jenkins/inbound-agent:latest        
> jenkins/inbound-agent@sha256:296579aa37138cd1ea493efb5e554e2061a8f851a46762c32bfdebe9d0d71aa3
> ```

I'm also experiencing this issue where `jenkins/inbound-agent:latest` points to `jenkins/inbound-agent:4.11.2-3-jdk11` instead of `jenkins/inbound-agent:4.11.2-4-jdk11` @timja

**Comment by timja** [comment]
Seems okay for me?
```
➜  . git:(master) docker pull jenkins/inbound-agent && docker inspect jenkins/inbound-agent | grep \"Version
Using default tag: latest
latest: Pulling from jenkins/inbound-agent
Digest: sha256:dd69fb14dcfbc06391b9aed5420e8ab8df1f93ff841bf2f6a77c8ac5607d16f6
Status: Image is up to date for jenkins/inbound-agent:latest
docker.io/jenkins/inbound-agent:latest
                "Version": "4.11.2-4-jdk11",
```

**Comment by tynril** [comment]
FYI, builds using `jenkins/inbound-agent:latest` have been failing for the last 5+ hours on our end, while `jenkins/inbound-agent:4.11.2-4-jdk11` are succeeding. There's definitely a difference between the two.

**Comment by timja** [comment]
do you get the same result as me?

**Comment by MarkEWaite** [comment]
> Seems okay for me?
> 
> ```
> $ docker pull jenkins/inbound-agent && docker inspect jenkins/inbound-agent | grep \"Version
> Using default tag: latest
> latest: Pulling from jenkins/inbound-agent
> Digest: sha256:dd69fb14dcfbc06391b9aed5420e8ab8df1f93ff841bf2f6a77c8ac5607d16f6
> Status: Image is up to date for jenkins/inbound-agent:latest
> docker.io/jenkins/inbound-agent:latest
>                 "Version": "4.11.2-4-jdk11",
> ```

I see

```
$ docker pull jenkins/inbound-agent && docker inspect jenkins/inbound-agent | grep \"Version
Using default tag: latest
latest: Pulling from jenkins/inbound-agent
Digest: sha256:dd69fb14dcfbc06391b9aed5420e8ab8df1f93ff841bf2f6a77c8ac5607d16f6
Status: Image is up to date for jenkins/inbound-agent:latest
docker.io/jenkins/inbound-agent:latest
                "Version": "4.11.2-4-jdk11",

# Surprising result in next command, ask for 4.11.2-3 but Version reports 4.11.2-4
$ docker pull jenkins/inbound-agent:4.11.2-3-jdk11 && docker inspect jenkins/inbound-agent:4.11.2-3-jdk11 | grep \"Version
4.11.2-3-jdk11: Pulling from jenkins/inbound-agent
Digest: sha256:dd69fb14dcfbc06391b9aed5420e8ab8df1f93ff841bf2f6a77c8ac5607d16f6
Status: Image is up to date for jenkins/inbound-agent:4.11.2-3-jdk11
docker.io/jenkins/inbound-agent:4.11.2-3-jdk11
                "Version": "4.11.2-4-jdk11",

# Expected result in next command, ask for 4.11.2-1 aand Version reports 4.11.2-1
$ docker pull jenkins/inbound-agent:4.11.2-1-jdk11 && docker inspect jenkins/inbound-agent:4.11.2-1-jdk11 | grep \"Version
4.11.2-1-jdk11: Pulling from jenkins/inbound-agent
Digest: sha256:c9aa4e55f3aab902db401599defa06e15cc9d4b39b6127ab41564907114caa37
Status: Image is up to date for jenkins/inbound-agent:4.11.2-1-jdk11
docker.io/jenkins/inbound-agent:4.11.2-1-jdk11
                "Version": "4.11.2-1-jdk11",
```

When I compare the "Digest" values from hub.docker.com, I see that `latest` on amd64 has the digest `a6b439097ffa`.  That is the same "Digest" value as is used in the [4.11.2-3 Docker container](https://hub.docker.com/layers/jenkins/inbound-agent/4.11.2-3-jdk11/images/sha256-a6b439097ffa3e4c2f16737fd8c0b3ecc0c4ad3752aa87b9a87115c1c9098986?context=explore).

I can't explain why example 1 (`latest`) reports 4.11.2-4 yet the Digest for `latest` on hub.docker.com seems to match the digest for 4.11.2-3.  I can't explain why example 2 (4.11.2-3) pulls 4.11.2-3 and yet the version string inside the container is 4.11.2-4.

**Comment by amitlalani** [comment]
> Seems okay for me?
> 
> ```
> ➜  . git:(master) docker pull jenkins/inbound-agent && docker inspect jenkins/inbound-agent | grep \"Version
> Using default tag: latest
> latest: Pulling from jenkins/inbound-agent
> Digest: sha256:dd69fb14dcfbc06391b9aed5420e8ab8df1f93ff841bf2f6a77c8ac5607d16f6
> Status: Image is up to date for jenkins/inbound-agent:latest
> docker.io/jenkins/inbound-agent:latest
>                 "Version": "4.11.2-4-jdk11",
> ```

When checking the version I get the same output as you but when comparing the digests similar to @MarkEWaite above, `latest` is still pointing to `4.11.2-3` and my builds using `latest` are still failing but pass when using `4.11.2-4`

**Comment by tynril** [comment]
Using `docker pull jenkins/inbound-agent:<tag> && docker inspect jenkins/inbound-agent:<tag>`, I'm getting the following result:

```
Tag                                     RepoDigest                                                                  Id
jenkins/inbound-agent:latest            sha256:dd69fb14dcfbc06391b9aed5420e8ab8df1f93ff841bf2f6a77c8ac5607d16f6     sha256:f23812a369eb1a51fbddcb47fef5236a90f146d8520a41440dd30280eeeeb9cf
jenkins/inbound-agent:4.11.2-4-jdk11    sha256:0de6d1feaee946c0be1805edc11e5445953582a91f6769b0cdae570d515ba1d6     sha256:c63bdb080b3423aa77de24cbfd53e8296aee0e5d2be360ec8a4e2598f8f1b39c
jenkins/inbound-agent:4.11.2-3-jdk11    sha256:dd69fb14dcfbc06391b9aed5420e8ab8df1f93ff841bf2f6a77c8ac5607d16f6     sha256:f23812a369eb1a51fbddcb47fef5236a90f146d8520a41440dd30280eeeeb9cf
```

`latest` is currently the same as `4.11.2-3-jdk11`.

**Comment by timja** [comment]
I rebuilt the release and seems to be right now:
```
docker pull jenkins/inbound-agent:latest && docker pull jenkins/inbound-agent:4.11.2-4-jdk11 && docker pull jenkins/inbound-agent:4.11.2-3-jdk11

➜  github-checks-plugin git:(reuse_build_params) docker inspect jenkins/inbound-agent | grep RepoDigest -A 1
        "RepoDigests": [
            "jenkins/inbound-agent@sha256:8cb43aa874cec78226fdb3e8dce1968d56caddcd56ea368fb64f7d81b242341d"
➜  github-checks-plugin git:(reuse_build_params) docker inspect jenkins/inbound-agent:4.11.2-4-jdk11 | grep RepoDigest -A 1
        "RepoDigests": [
            "jenkins/inbound-agent@sha256:8cb43aa874cec78226fdb3e8dce1968d56caddcd56ea368fb64f7d81b242341d"
➜  github-checks-plugin git:(reuse_build_params) docker inspect jenkins/inbound-agent:4.11.2-3-jdk11 | grep RepoDigest -A 1
        "RepoDigests": [
            "jenkins/inbound-agent@sha256:dd69fb14dcfbc06391b9aed5420e8ab8df1f93ff841bf2f6a77c8ac5607d16f6"
```

**Comment by MarkEWaite** [comment]
Thanks very much @timja !  I've confirmed that the digest reported on hub.docker.com for `latest` matches the digest reported on hub.docker.com for `4.11.2-4-jdk11`

**Comment by tynril** [comment]
Things are looking correct now on our end too, thank you!

```
Tag                                     RepoDigest                                                                  Id
jenkins/inbound-agent:4.11.2-4-jdk11    sha256:8cb43aa874cec78226fdb3e8dce1968d56caddcd56ea368fb64f7d81b242341d     sha256:4c6bc506fbdc4437b5476c603d85de42c742054d975d42cd27463751dcddc044
jenkins/inbound-agent:latest            sha256:8cb43aa874cec78226fdb3e8dce1968d56caddcd56ea368fb64f7d81b242341d     sha256:4c6bc506fbdc4437b5476c603d85de42c742054d975d42cd27463751dcddc044
```

**Comment by bversteegh** [comment]
Do the [jenkins/jnlp-agent](https://hub.docker.com/r/jenkins/jnlp-agent-docker/tags) images also need to be rebuilt? They use jenkins/inbound-agent:alpine as the [base layer](https://github.com/jenkinsci/jnlp-agents/blob/master/docker/Dockerfile) and were working after this fix was merged yesterday, however now seem to be broken after something rebuilt them 8hrs ago.

**Comment by MarkEWaite** [comment]
> Do the [jenkins/jnlp-agent](https://hub.docker.com/r/jenkins/jnlp-agent-docker/tags) images also need to be rebuilt? They use jenkins/inbound-agent:alpine as the [base layer](https://github.com/jenkinsci/jnlp-agents/blob/master/docker/Dockerfile) and were working after this fix was merged yesterday, however now seem to be broken after something rebuilt them 8hrs ago.

I don't think that a rebuild of that image is needed for this issue, since the base image in `jenkins/jnlp-agent-docker:latest` seems to be `4.11.2-4-alpine-jdk11`.  The issue was introduced in `4.11.2-3` and fixed in `4.11.2-4`.

```
$ docker pull jenkins/jnlp-agent-docker:latest && docker inspect jenkins/jnlp-agent-docker:latest | grep -F '"Version'
latest: Pulling from jenkins/jnlp-agent-docker
Digest: sha256:fc2242b7f34013e6cbfc70ffe54c0e1a9b66414237b6e5ee4996c3829add6a88
Status: Image is up to date for jenkins/jnlp-agent-docker:latest
docker.io/jenkins/jnlp-agent-docker:latest
                "Version": "4.11.2-4-alpine-jdk11",
                "Version": "4.11.2-4-alpine-jdk11",
```

**Comment by bversteegh** [comment]
Ok thats strange, the jnlp agent images were working for us yesterday after this fix was merged & built. However based on dockerhub it looks like the jnlp image were built again 8hrs ago and now we're getting the same behaviour again with the jnlp image terminating immediately

**Comment by MarkEWaite** [comment]
I'm not sure of the purpose or use of the `jenkins/jnlp-agent-docker` image.  It seems to have one and only one tag, `latest`.

**Comment by bversteegh** [comment]
My understanding is that they are Jenkins provided jnlp images in various flavours, with different tooling preinstalled, sourced from here: https://github.com/jenkinsci/jnlp-agents. They seem to be based off the inbound agent with additional installs on top.

**Comment by bversteegh** [comment]
Ok so an update, 
Running `docker pull jenkins/jnlp-agent-docker:latest && docker inspect jenkins/jnlp-agent-docker:latest | grep -F '"Version'` returns `"Version": "4.11.2-4-alpine-jdk11"` as you are seeing.

However if I ` docker run -it jenkins/jnlp-agent-docker /bin/sh` locally, and cat "/usr/local/bin/jenkins-agent", I get this:
```
#!/usr/bin/env bash

# The MIT License
<truncating text>

if [ "${1:0:1}" != '-' ]; then
```

Which are the changes that should have been reverted by 4.11.2-4?
It feels like when the jnlp agent image was rebuilt earlier, it was also affected by the latest != latest issue that the others have seen. I think if we could get these downstream jnlp agent images rebuilt then this should solve the problem now that the inbound agent tags have been fixed.

**Pull request merged**
