### PR TITLE
[INFRA-1105] - Update the base image to jenkins/agent:4.3-4, cleanup old metadata

### PR DESCRIPTION
**Pull request by oleg-nenashev**
This PR picks up agent renaming in https://issues.jenkins-ci.org/browse/INFRA-1105 . After this change both Linux and Windows base images will be under the same roof for us.

I also cleaned up old `MAINTAINER` metadata and ducplicated `ARG VERSION` in Windows images. They are harmless, but it is better to keep the metadata clean.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Blocked by https://issues.jenkins-ci.org/browse/INFRA-2570 which prevents release of the base image

**Comment by slide** [comment]
I think the issue with the base image is resolved. The windows agents are up on ci.j.io and trusted

**Comment by slide** [comment]
These need to be 4.3-4 now, correct?

**Comment by oleg-nenashev** [comment]
yes, on it

**Pull request merged**
