### PR TITLE
Upgrade remoting to 4.9

### PR DESCRIPTION
**Pull request by agentgonzo**
See https://github.com/jenkinsci/docker-agent/pull/176

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by olblak — APPROVED** [review]
🚀

**Comment by agentgonzo** [comment]
@slide :
`manifest for jenkins/agent:4.9-1-alpine not found: manifest unknown: manifest unknown`

_should_ this image exist? (I can see it doesn't but [4.7-1-alpine](https://hub.docker.com/r/jenkins/agent/tags?page=1&ordering=last_updated&name=4.7-1-alpine) does exist

**Comment by slide** [comment]
It looks like some builds failed on dockerhub for some reason. I will relaunch them

**Comment by agentgonzo** [comment]
@olblak - the offending docker image [now exists](https://hub.docker.com/layers/jenkins/agent/4.9-1-alpine/images/sha256-62374e3e420382764760cc2d2c35d7e34f45291249dcc8785a79052255bc8a6a?context=explore). Can you retrigger a build please to get Jenkins to pass the build?

**Comment by slide** [comment]
I retriggered it, running now

**Pull request merged**
