### PR TITLE
Provide image which is based on Debian 10/buster

### PR DESCRIPTION
**Pull request by krichter722**
Requires https://github.com/jenkinsci/docker-slave/pull/106 to be merged and the image to be available (the version might need change after the image has been published).

### CODE REVIEW

**Comment by rtyler** [comment]
@krichter722 this looks the exact same as #106, what am I missing?

**Comment by krichter722** [comment]
@rtyler As far as I understand, this JNLP slave image is based on the base slave image for which a `jdk11-buster` image needed to be created first in order to be able to use it here. As soon as the base image is published, this build can succeed and JNLP slave image for `jdk11-buster` is provided.

I assume you mean https://github.com/jenkinsci/docker-slave/pull/106 when you link #106 :) Then the above explanation should apply, otherwise, please elaborate on the similarities, please.

**Comment by rtyler** [comment]
@krichter722 correct, I did not notice that these were on two different repositories :smile_cat:

**Comment by slide** [comment]
I think this is done because all of our images are default buster now. @oleg-nenashev is that correct?

**Comment by oleg-nenashev** [comment]
Yes. We merged https://github.com/jenkinsci/docker-agent/pull/106 , and Buster is a default image starting from `jenkins/agent:4.3-2`: https://github.com/jenkinsci/docker-agent/releases/tag/4.3-2 . So this part is delivered in the default images  starting from `jenkins/inbound-agent:4.3-2`

**Comment by oleg-nenashev** [comment]
Thanks @krichter722 for the update! I will close this PR as discussed above

**Pull request closed without merging**
