### PR TITLE
Adding debian_jdk21 to ppc64le build list to test

### PR DESCRIPTION
**Pull request by ksalerno99**
docker-agent:jdk21-preview being built

Thank you @gounthar for adding jdk21-preview to the docker-agent build. I have tested that and would like to add debian_jdk21 to the ppc64le list for the inbound agent to test.

### Testing done
I tested the build for the following releases:
2.414.1 (LTS)	f2523f9b5fe50199f68f60f96b6bef9ca100e18099e3e3da7a9a49ae8c47b015
2.419		895a90dd5929a38c8cc8c0342478d27a6e01470cd7e8da8c4ae51f26aa1bdf85
2.423 (weekly)	d768d6f7d77b2916eb86838887278f603b60a6cce88389c606eb310321c2689e

cd docker; make list:
debian_jdk11
debian_jdk17
debian_jdk21
debian_slim_jdk21
rhel_ubi9_jdk17
rhel_ubi9_jdk21

cd docker-agent; make list:
debian_jdk11
debian_jdk17
debian_jdk21

cd docker-inbound-agent; make list:
debian_jdk11
debian_jdk17
debian_jdk21 <---- added this myself and created this PR

cd docker-ssh-agent; make list:
debian_jdk11
debian_jdk21

```[tasklist]
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by ksalerno99** [comment]
Note: the check above will fail until docker.io/jenkins/agent:3148.v532a_7e715ee3-5-jdk21-preview appears in the repo for ppc64le. (I added this tag to docker-agent:jdk21-preview manually in my environment for testing purposes.)

**Comment by ksalerno99** [comment]
Testing results for my own docker-inbound-agent build:

```
Started by user [Kenneth Paul Salerno](http://172.27.138.113:8080/user/kens)
Running as SYSTEM
Building remotely on [docker-inbound-agent](http://172.27.138.113:8080/computer/docker-inbound-agent) in workspace /home/jenkins/agent/workspace/Test docker-inbound-agent
[Test docker-inbound-agent] $ /bin/sh -xe /tmp/jenkins5636706266719725989.sh
+ java -version
openjdk version "21-beta" 2023-09-19
OpenJDK Runtime Environment Temurin-21+35-202308221544 (build 21-beta+35-ea)
OpenJDK 64-Bit Server VM Temurin-21+35-202308221544 (build 21-beta+35-ea, mixed mode)
+ echo docker-inbound-agent
docker-inbound-agent
Finished: SUCCESS
```

**Comment by dduportal** [comment]
The 3148.v532a_7e715ee3-6-jdk21-preview release should published in the next few minutes : you can update the PR then.

LGTM then, this really cool 👍🏼

**Comment by ksalerno99** [comment]
> The 3148.v532a_7e715ee3-6-jdk21-preview release should published in the next few minutes : you can update the PR then.
> 
> LGTM then, this really cool 👍🏼

Thanks! How do I update this PR? Should I click "Update branch" to force the checks to re-run?

**Comment by dduportal** [comment]
> > The 3148.v532a_7e715ee3-6-jdk21-preview release should published in the next few minutes : you can update the PR then.
> > LGTM then, this really cool 👍🏼
> 
> Thanks! How do I update this PR? Should I click "Update branch" to force the checks to re-run?

Ideally yes, but the changes you introduced are already good even without rebasing / merging #407 .

Tim merged and the main CI build looks good \o/

Thanks!


(please note that we will have to release this change as part of an upcoming `3148.v532a_7e715ee3-7` version as the `3148.v532a_7e715ee3-6` was already released (keeping `jenkins/agent` and `jenkins/inbound-agent` tags in sync avoid user confusion. Cc @lemeurherve @timja another argument in favor of merging repositories for the agent and inbound agent to allow an improved release planning)

**Comment by dduportal** [comment]
Thanks to @lemeurherve , it is deployed as https://github.com/jenkinsci/docker-inbound-agent/releases/tag/3148.v532a_7e715ee3-7

Capture d’écran 2023-09-15 à 20 33 19

**Pull request merged**
