### PR TITLE
feat(Windows): add Java 21 and bump `jenkins/agent` parent images to `3148.v532a_7e715ee3-12`

### PR DESCRIPTION
**Pull request by lemeurherve**
This PR adds jdk21 variants for Windows images.

Needs images from https://github.com/jenkinsci/docker-agent/pull/518, includes and closes https://github.com/jenkinsci/docker-inbound-agent/pull/421

### Testing done

https://ci.jenkins.io/job/Packaging/job/docker-inbound-agent/job/PR-418/6/

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Review by dduportal — COMMENTED** [review]
LGTM, nice work!

Do you mind updating the title to mention the bump to `3148.v532a_7e715ee3-12`?

**Comment by dduportal** [comment]
Btw, can we wait for https://github.com/jenkinsci/docker-inbound-agent/pull/422 before merging here?

**Comment by lemeurherve** [comment]
Title updated, waiting for #422 to be released, PR ready for review/approval.

**Comment by lemeurherve** [comment]
Merge conflicts fixed, #422 released: https://github.com/jenkinsci/docker-inbound-agent/releases/tag/3148.v532a_7e715ee3-11

**Review by dduportal — APPROVED** [review]

**Pull request merged**
